const express = require("express");
const { createProduct, readProduct, deleteProduct, updateProduct } = require("../controllers/ProductController");
const { createUser, readUser, deleteUser, updateUser } = require("../controllers/userController");
const { createAdmin, readAdmin, deleteAdmin, updateAdmin } = require("../controllers/adminController");
const { createCart, readCart, deleteCart, updateCart } = require("../controllers/cartController");
const { createCategory, readCategory, deleteCategory, updateCategory } = require("../controllers/categoryController");
const { createCustomer, readCustomer, deleteCustomer, updateCustomer } = require("../controllers/customerController");
const { createOrderItem, readOrderItem, deleteOrderItem, updateOrderItem } = require("../controllers/order_itemController");
const { createOrder, readOrder, deleteOrder, updateOrder } = require("../controllers/orderController");
const { createPayment, readPayment, deletePayment, updatePayment } = require("../controllers/paymentController");
const { createPost, readPost, deletePost, updatePost } = require("../controllers/postController");
const { createShipment, readShipment, deleteShipment, updateShipment } = require("../controllers/shipmentController");
const { createSubAdmin, readSubAdmin, deleteSubAdmin, updateSubAdmin } = require("../controllers/subAdminController");
const { createWishList, readWishList, deleteWishList, updateWishList } = require("../controllers/wishlistController");

const router = express.Router();


router.get("/createProduct", createProduct);
router.get("/readProduct", readProduct);
router.get("/deleteProduct", deleteProduct);
router.get("/updateProduct", updateProduct);
router.get("/createUser", createUser);
router.get("/readUser", readUser);
router.get("/deleteUser", deleteUser);
router.get("/updateUser", updateUser);
router.get("/createAdmin", createAdmin);
router.get("/readAdmin", readAdmin);
router.get("/deleteAdmin", deleteAdmin);
router.get("/updateAdmin", updateAdmin);
router.get("/createCart", createCart);
router.get("/readCart", readCart);
router.get("/deleteCart", deleteCart);
router.get("/updateCart", updateCart);
router.get("/createCategory", createCategory);
router.get("/readCategory", readCategory);
router.get("/deleteCategory", deleteCategory);
router.get("/updateCategory", updateCategory);
router.get("/createCustomer", createCustomer);
router.get("/readCustomer", readCustomer);
router.get("/deleteCustomer", deleteCustomer);
router.get("/updateCustomer", updateCustomer);
router.get("/createOrderItem", createOrderItem);
router.get("/readOrderItem", readOrderItem);
router.get("/deleteOrderItem", deleteOrderItem);
router.get("/updateOrderItem", updateOrderItem);
router.get("/createOrder", createOrder);
router.get("/readOrder", readOrder);
router.get("/deleteOrder", deleteOrder);
router.get("/updateOrder", updateOrder);
router.get("/createPayment", createPayment);
router.get("/readPayment", readPayment);
router.get("/deletePayment", deletePayment);
router.get("/updatePayment", updatePayment);
router.get("/createPost", createPost);
router.get("/readPost", readPost);
router.get("/deletePost", deletePost);
router.get("/updatePost", updatePost);
router.get("/createShipment", createShipment);
router.get("/readShipment", readShipment);
router.get("/deleteShipment", deleteShipment);
router.get("/updateShipment", updateShipment);
router.get("/createSubAdmin", createSubAdmin);
router.get("/readSubAdmin", readSubAdmin);
router.get("/deleteSubAdmin", deleteSubAdmin);
router.get("/updateSubAdmin", updateSubAdmin);
router.get("/createWishList", createWishList);
router.get("/readWishList", readWishList);
router.get("/deleteWishList", deleteWishList);
router.get("/updateWishList", updateWishList);


module.exports = router;
